package com.epam.xsl.command.factory;

/**
 * <code>CommandEnum</code> is needed to point on appropriate command in JSP.
 * 
 * @author Yra
 *
 */
public enum CommandEnum {
	LOGIN, SHOW_ELECTIVE, SHOW_TEACHER, SHOW_STUDENT, GET_NEW_ELECTIVE_FORM,
	CREATE_ELECTIVE, SET_MARK_TO_STUDENT, GET_FORM_TO_SET_MARK,
	SHOW_STUDENT_MARKS, DELETE_ELECTIVE, GET_REGISTRATION_FORM, REGISTER_AS_STUDENT,
	REGISTER_AS_TEACHER, BECOME_A_TEACHER_OF_ELECTIVE, BECOME_A_LISTENER_OF_ELECTIVE,
	RESIGN_FROM_ELECTIVE, LOGOUT, TO_MAIN_PAGE, TO_PREVIOUS_PAGE,
	SET_ENGLISH_LANGUAGE, SET_RUSSIAN_LANGUAGE, NO_COMMAND
}
